const mongoose = require('mongoose');
const dns = require("node:dns");
dns.setServers(["8.8.8.8", "1.1.1.1"]);

const DB_URI = "mongodb+srv://gujjarkaleem37_db_user:kaleem217@cluster0.jzi2xz0.mongodb.net/ecommerce?retryWrites=true&w=majority";

// Import Models
require('./src/models/coreModels/Admin');
require('./src/models/appModels/Client');
require('./src/models/appModels/Invoice');
require('./src/models/appModels/Expense');

const Admin = mongoose.model('Admin');
const Client = mongoose.model('Client');
const Invoice = mongoose.model('Invoice');
const Expense = mongoose.model('Expense');

async function seed() {
  try {
    console.log('Connecting to database...');
    await mongoose.connect(DB_URI);
    console.log('Connected!');

    const admin = await Admin.findOne();
    const client = await Client.findOne();

    if (!admin || !client) {
      console.error('Error: Need at least one Admin and one Client to seed data.');
      process.exit(1);
    }

    console.log('Cleaning old AI data...');
    // Only clean data generated by this seeder or mark them
    await Invoice.deleteMany({ notes: 'AI_SEED_DATA' });
    await Expense.deleteMany({ description: 'AI_SEED_DATA' });

    const months = [
      { name: 'Mar 2025', date: new Date(2025, 2, 15), rev: 4500, exp: 3200 },
      { name: 'Apr 2025', date: new Date(2025, 3, 15), rev: 4800, exp: 3100 },
      { name: 'May 2025', date: new Date(2025, 4, 15), rev: 5200, exp: 3400 },
      { name: 'Jun 2025', date: new Date(2025, 5, 15), rev: 5000, exp: 3300 },
      { name: 'Jul 2025', date: new Date(2025, 6, 15), rev: 5500, exp: 3600 },
      { name: 'Aug 2025', date: new Date(2025, 7, 15), rev: 6000, exp: 3800 },
      { name: 'Sep 2025', date: new Date(2025, 8, 15), rev: 5800, exp: 3700 },
      { name: 'Oct 2025', date: new Date(2025, 9, 15), rev: 6200, exp: 4000 },
      { name: 'Nov 2025', date: new Date(2025, 10, 15), rev: 7000, exp: 4200 },
      { name: 'Dec 2025', date: new Date(2025, 11, 15), rev: 8500, exp: 5000 }, // Holiday surge
      { name: 'Jan 2026', date: new Date(2026, 0, 15), rev: 6500, exp: 3900 },
      { name: 'Feb 2026', date: new Date(2026, 1, 15), rev: 6800, exp: 4100 },
      { name: 'Mar 2026', date: new Date(2026, 2, 15), rev: 7200, exp: 4300 },
    ];

    console.log('Seeding 13 months of data...');

    for (const m of months) {
      // Seed Invoice
      await new Invoice({
        createdBy: admin._id,
        number: Math.floor(Math.random() * 10000),
        year: m.date.getFullYear(),
        date: m.date,
        expiredDate: new Date(m.date.getTime() + 30 * 24 * 60 * 60 * 1000),
        client: client._id,
        items: [{ itemName: 'Consulting', quantity: 1, price: m.rev, total: m.rev }],
        subTotal: m.rev,
        total: m.rev,
        currency: 'USD',
        status: 'sent',
        paymentStatus: 'paid',
        notes: 'AI_SEED_DATA'
      }).save();

      // Seed Expense
      await new Expense({
        createdBy: admin._id,
        title: `Monthly Operations - ${m.name}`,
        amount: m.exp,
        date: m.date,
        category: 'Operations',
        description: 'AI_SEED_DATA',
        status: 'Approved'
      }).save();
    }

    console.log('Seeding Complete! AI Intelligence Activated.');
    process.exit(0);
  } catch (err) {
    console.error('Seeding Failed:', err);
    process.exit(1);
  }
}

seed();
